### ISSUE TITLE
QS-Findings zum Jahreswechsel

### ISSUE THREAD

**Issue by marievk** [opendataddorf/od-resources#2]
Hallo, 
schön, dass es hier nun wieder Zahlen gibt! Folgendes fällt auf (Stand 10.01.2022): 
- Es fehlen "bestaetigte Faelle kumulativ" und die "7-Tages-Inzidenz" vom 23. bis 27.12.2021.
- Für den 05.01.2022 fehlen zumindest 42.000 "Genesene", am 23.12.2021 zumindest 600. 
- Das Delta zwischen "bestaetigte Faelle kumulativ" und der Summe "Aktive Faelle" + "Genesene" + "Todesfaelle" ist ab Ende Dezember vglw. groß. 
- Die "Aktive Faelle" erscheinen aktuell (zu) niedrig angesetzt, für den 10.01.2022 z.b. mit 5.500 < Summe Zuwachs "bestaetigte Faelle kumulativ" seit dem 29.12.2021: 5.703 (für 13 Tage).

**Comment by ZelOpen** [comment]
Die fehler wurden korrigiert

**Comment by marievk** [comment]
Danke. Der letzte Punkt wirkt noch offen. Stand gestern (02.02.) sehe ich zusätzlich:
- Die für den 28.01. ausgewiesenen "bestaetigten Faelle kumulativ" (69.874) passt nicht zur Summe über "Aktive Faelle" (16.000), "Genesene" (57.200) und "Todesfaelle" - diese 3 Einträge sind wohl redundant zu denen vom 29.01.
- Bei 25.675 Infektionen/Fällen innerhalb der letzten 7 Tage und ~640.000 Einwohnern erscheint die hier angegebene Inzidenz zudem deutlich (!) zu niedrig. Beginnend um den 22.01. herum zeigt sich eine zunehmende Differenz.

**Comment by ZelOpen** [comment]
> Danke. Der letzte Punkt wirkt noch offen. Stand gestern (02.02.) sehe ich zusätzlich:
> 
>     * Die für den 28.01. ausgewiesenen "bestaetigten Faelle kumulativ" (69.874) passt nicht zur Summe über "Aktive Faelle" (16.000), "Genesene" (57.200) und "Todesfaelle" - diese 3 Einträge sind wohl redundant zu denen vom 29.01.
> 
>     * Bei 25.675 Infektionen/Fällen innerhalb der letzten 7 Tage und ~640.000 Einwohnern erscheint die hier angegebene Inzidenz zudem deutlich (!) zu niedrig. Beginnend um den 22.01. herum zeigt sich eine zunehmende Differenz.

Danke für die Hinweise. 

- zum ersten Punkt haben wir alle Daten nochmal überprüft und korrigiert. 
- das Gesundheitsamt der Landeshauptstadt Düsseldorf war wie andere Kommunen von den Störungen durch ein bundesweites Update der Meldesoftware des Robert Koch-Instituts betroffen gewesen. Die für die Landeshauptstadt berichteten Inzidenzen weichen daher temporär von den tatsächlichen Inzidenzen ab.
